### ISSUE TITLE
Add tips about where to find more shapefiles

### ISSUE THREAD

**Issue by theold190** [doersino/aerialbot#4]
Very cool and interesting project. What about adding support for other countries? For example, there are shapefiles for European countries available here: https://www.eea.europa.eu/data-and-maps/data/eea-reference-grids-2/gis-files/folder_listing. Some have different resolution (?) - 1km, 10km, 100km (ex. Sweden).

Does it make sense to add them to the repository, make tool download files or maybe just mention in the README.md?

This might both save time for others and could be used as extra way to demonstrate aerialbot for others.

**Comment by doersino** [comment]
Sadly, the shapefiles you've linked aren't of the type that ærialbot expects. I've thrown the Sweden ones into [mapshaper.org](https://mapshaper.org) and noticed the following:

* They contain multiple records per file, but this could be fixed with mapshaper as described [here](https://github.com/doersino/aerialbot/blob/master/shapefiles/README.md).
* The projection isn't based on latitude and longitude, but this, too, can be fixed.
* Yet most importantly, these shapefile contain differently-scaled variants *of the [EEA reference grid](https://www.eea.europa.eu/data-and-maps/data/eea-reference-grids-2)* corresponding to the countries. This grid doesn't follow coastlines or borders – in fact, it includes "at least country borders - plus 15km buffer - and, where applicable, marine Exclusive Economic Zones v7.0 - plus 15km buffer".

If you

1. can find a different set of shapefiles that are published under a license that allows inclusion in this repository *and*
2. are willing to do the work of coercing them into the [correct format](https://github.com/doersino/aerialbot/blob/master/shapefiles/README.md) if required,

please feel free to send a pull request! However, it's usually fairly easy to find shapefiles of country borders by searching¹ for "shapefile <country> borders" or similar, so it's probably not all that useful to preemptively add shapefiles that no one might ever use. What's more, the existing example shapefiles are probably sufficient for demonstration purposes.

Your suggestion of mentioning shapefile sources in `README.md` is good, though – I'll definitely add a section on that soon, thank you!

---

¹ While performing a search like that, I just came across [this page](https://gadm.org/download_country_v3.html) which appears to have shapefiles for all countries – and they seem to be ready for use with ærialbot out of the box (but I haven't tested that yet). Their [license](https://gadm.org/license.html), however, doesn't allow redistribution, so I can't include them in this repository.

**Comment by theold190** [comment]
Thanks for an answer and extra details!

I have tried to use shapefiles from my link and saw the issues you have named. The shapefiles on GADM are different and work from the box.
